# Generated by Django 4.2 on 2025-06-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact Submission', 'verbose_name_plural': 'Contact Submissions'},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='is_read',
        ),
        migrations.AddField(
            model_name='contact',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes for admin'),
        ),
        migrations.AddField(
            model_name='contact',
            name='category',
            field=models.CharField(choices=[('general', 'General Inquiry'), ('booking', 'Booking Support'), ('destinations', 'Destination Info'), ('feedback', 'Feedback'), ('partnership', 'Partnership'), ('technical', 'Technical Support')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='newsletter',
            field=models.BooleanField(default=False, help_text='Subscribe to newsletter'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, help_text='Optional phone number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(help_text='Email address for response', max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(help_text='Detailed message or inquiry'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(help_text='Full name of the contact', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(help_text='Subject of the inquiry', max_length=200),
        ),
    ]
