# Generated by Django 4.2 on 2025-06-12 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('destinations', '0001_initial'),
        ('bookings', '0002_rename_cancellation_reason_booking_dietary_restrictions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingtraveler',
            name='departure_date',
        ),
        migrations.RemoveField(
            model_name='bookingtraveler',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='bookingtraveler',
            name='number_of_travelers',
        ),
        migrations.RemoveField(
            model_name='bookingtraveler',
            name='return_date',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinations.destination'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_travelers',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(default='confirmed', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
