# Generated by Django 4.2 on 2025-06-13 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_destination_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='image_url',
        ),
    ]
