# Generated by Django 4.2 on 2025-06-13 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0003_remove_destination_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the favorite list', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the favorite list')),
                ('is_public', models.BooleanField(default=False, help_text='Whether this list is visible to other users')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Personal notes about this destination')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinations.destination')),
                ('favorite_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='favorites.favoritelist')),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('favorite_list', 'destination')},
            },
        ),
        migrations.AddField(
            model_name='favoritelist',
            name='destinations',
            field=models.ManyToManyField(related_name='in_favorite_lists', through='favorites.FavoriteListItem', to='destinations.destination'),
        ),
        migrations.AddField(
            model_name='favoritelist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the destination was favorited')),
                ('destination', models.ForeignKey(help_text='Destination that was favorited', on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='destinations.destination')),
                ('user', models.ForeignKey(help_text='User who favorited the destination', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite Destination',
                'verbose_name_plural': 'Favorite Destinations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='favoritelist',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user', '-created_at'], name='favorites_f_user_id_3c3f17_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['destination', '-created_at'], name='favorites_f_destina_a52216_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'destination')},
        ),
    ]
